server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    # 指定数据源类型为DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库连接URL
      url: jdbc:mysql://127.0.0.1:7033/chenj-oa?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
      # 数据库用户名
      username: root
      # 数据库密码
      password: root
      # 连接池初始化时创建的连接数
      initialSize: 5
      # 连接池中最大连接数
      maxActive: 50
      # 连接池中最小空闲连接数
      minIdle: 5
      # 连接池中最大空闲连接数
      maxIdle: 10
      # 获取连接时的最大等待时间（毫秒）
      maxWait: 60000
      # 间隔多久检测一次空闲连接（毫秒）
      timeBetweenEvictionRunsMillis: 60000
      # 连接池中连接最小空闲时间（毫秒）
      minEvictableIdleTimeMillis: 300000
      # 用于检测连接是否有效的SQL语句
      validationQuery: SELECT 1
      # 是否开启空闲连接的检测
      testWhileIdle: true
      # 是否开启连接的检测功能，在获取连接时检测连接是否有效
      testOnBorrow: false
      # 是否开启连接的检测功能，在归还连接时检测连接是否有效
      testOnReturn: false
      # 是否缓存PreparedStatement对象
      poolPreparedStatements: true
      # 缓存PreparedStatement对象的最大数量
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计用的filter，允许监控统计
      filters: stat
      # 配置扩展属性，用于监控统计分析SQL性能等
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000